name: my_kutsev
channels:
  - defaults
dependencies:
  - attrs=23.1.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - certifi=2024.8.30
  - cfitsio=3.470
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - expat=2.6.3
  - fiona=1.9.5
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - minizip=4.0.3
  - ncurses=6.4
  - networkx=3.3
  - nltk=3.9.1
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - pybind11-abi=4
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - rtree=1.0.1
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - shapely=2.0.5
  - six=1.16.0
  - sqlite=3.45.3
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tqdm=4.66.5
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.2.2
  - wheel=0.43.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - xgboost==2.1.1
